# Generated by Django 4.0.2 on 2022-03-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duck',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
