# Generated by Django 4.0.2 on 2022-03-07 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_duck_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duck',
            old_name='location',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='duck',
            name='Image_Url',
        ),
    ]
