# Generated by Django 4.0.2 on 2022-04-20 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=40, null=True)),
                ('lname', models.CharField(blank=True, max_length=40, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('grade_level', models.IntegerField(blank=True, default=0, null=True)),
                ('xp', models.IntegerField(default=0)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField(choices=[(1, 'Veryeasy'), (2, 'Easy'), (3, 'Normal'), (4, 'Hard'), (5, 'Veryhard')])),
                ('recurring', models.BooleanField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('done_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField(choices=[(1, 'Veryeasy'), (2, 'Easy'), (3, 'Normal'), (4, 'Hard'), (5, 'Veryhard')])),
                ('xp', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('done_date', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
