# Generated by Django 4.0.2 on 2022-04-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlxp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_level',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
    ]
