# Generated by Django 4.0.2 on 2022-04-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlxp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chore',
            name='chore',
            field=models.BooleanField(default=True),
        ),
    ]
