# Generated by Django 4.0.2 on 2022-04-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rlxp', '0005_chore_xp_alter_assignment_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='xp',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='chore',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='xp',
        ),
    ]
