# Generated by Django 4.0.2 on 2022-04-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlxp', '0006_remove_assignment_xp_remove_chore_chore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
