# Generated by Django 4.0.2 on 2022-04-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlxp', '0007_alter_assignment_due_date_alter_chore_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='done_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='done_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='chore',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
