# Generated by Django 4.0.2 on 2022-04-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rlxp', '0009_alter_chore_done_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='xp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
